package com.goldfish.registration;

public enum ValidRegistrationStatusCodeEnum {
	REGISTRATION_VALIDATION_INVALID("250"), REGISTRATION_VALIDATION_TOO_MANY_ATTEMPTS("251"),
	REGISTRATION_VALIDATION_INVALID_ONE_ATTEMPT_LEFT("258"),
	REGISTRATION_VALIDATION_INVALID_PARAMETERS_VALUE("259"), ERROR_CODE_DESCRIPTION_PARAM_VALUE_NULL("111"),
	REGISTRATION_ACCOUNT_LOCKED("252"), REGISTRATION_PWD_STRENGTH("257"), USER_RSA_UNVERIFIED("240"),
	REGISTRATION_USERID_EXISTS("253"), REGISTRATION_VALID("255"), REGISTRATION_PWD_REUSED("256"),
	USER_RSA_DELETED("239"), USER_RSA_LOCKED("238"), USER_RSA_VERIFIED("237"), USER_RSA_UNLOCKED("241"),
	USER_RSA_NOT_ENROLLED("242");
	
	private String statusCode;

	private ValidRegistrationStatusCodeEnum(String s) {
		statusCode = s;
	}

	public String getStatusCode() {
		return statusCode;
	}
}
